# Generated by Django 5.2.7 on 2025-10-10 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('lugar', models.CharField(max_length=100)),
            ],
        ),
    ]
